[project]
name = "wikipedia-golf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "httpx>=0.28.1",
    "logfire>=4.32.1",
    "lxml>=6.1.0",
    "markdownify>=1.2.2",
    "pydantic>=2.13.3",
    "pydantic-ai>=1.90.0",
    "pydantic-evals>=0.2.0",
    "python-dotenv>=1.2.2",
    "tabulate>=0.10.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "pre-commit>=4.6.0",
]
